AWSTemplateFormatVersion: '2010-09-09'
Description: Transform rss text articles into podcasts
Parameters:
  Environment:
    Default: Development
    Type: String
Resources:
  pollyBucket:
    Type: AWS::S3::Bucket
  pollycast:
    Properties:
#      CodeUri: ./_build
      CodeUri: s3://sitalov-mac-duplicati/49d46efbe9efcab8d4cf2886b5775820
      Handler: podcast.lambda_handler
      Policies:
        - Statement:
            - Action:
                - polly:SynthesizeSpeech
                - s3:ListBucket
                - s3:PutObject
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
                - polly:SynthesizeSpeech
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Effect: Allow
              Resource:
                - '*'
          Version: '2012-10-17'
        - Statement:
            - Action:
                - s3:ListBucket
                - s3:PutObject
              Effect: Allow
              Resource:
                - Fn::GetAtt:
                    - pollyBucket
                    - Arn
          Version: '2012-10-17'
      Runtime: python3.6
      Timeout: 300
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31