service: podcast
provider:
  name: aws
  runtime: python2.7
  timeout: 300
  environment:
    AWS_REGION_BUCKET: "eu-west-1"
  iamRoleStatements:
      -  Effect: "Allow"
         Action:
           - "xray:PutTraceSegments"
           - "xray:PutTelemetryRecords"
           - "polly:SynthesizeSpeech"
           - "s3:ListBucket"
           - "s3:PutObject"
           - "logs:CreateLogGroup"
           - "logs:CreateLogStream"
           - "logs:PutLogEvents"
         Resource:
           - "*"
package:
  include:
    - .vendor/**
  artifact: package.zip

functions:
  handler:
    handler: podcast.handler
